//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "OrderPage.xaml.h"

void ::RestaurantManager::OrderPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///OrderPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::RestaurantManager::OrderPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->textSpecial = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 2:
            {
                this->textAddOrder = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->textAddOrder))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::RestaurantManager::OrderPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&OrderPage::textAddOrder_Tapped);
            }
            break;
        case 3:
            {
                this->textSubmitOrder = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->textSubmitOrder))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::RestaurantManager::OrderPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&OrderPage::textSubmitOrder_Click);
            }
            break;
        case 4:
            {
                this->listView1 = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
            }
            break;
        case 5:
            {
                this->listView2 = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
            }
            break;
        case 6:
            {
                this->appBar = safe_cast<::Windows::UI::Xaml::Controls::AppBar^>(__target);
            }
            break;
        case 7:
            {
                this->appBarHomeButton = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(this->appBarHomeButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::RestaurantManager::OrderPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&OrderPage::appBarHomeButton_Click);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::RestaurantManager::OrderPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


